trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - task: AzureFederatedAuth@1
    displayName: Get ARM OIDC token
    inputs:
      serviceConnectionARM: 'my-arm-service-connection'
      setGitAccessToken: true

  - bash: |
      set -euo pipefail
      if [[ -z "${ARM_OIDC_TOKEN:-}" ]]; then
        echo "ARM_OIDC_TOKEN is missing"
        exit 1
      fi
      echo "Token Hash: $(echo -n $ARM_OIDC_TOKEN | sha256sum | awk '{print $1}')"

      if [[ -z "${ARM_TENANT_ID:-}" ]]; then
        echo "ARM_TENANT_ID is missing"
        exit 1
      fi

      if [[ -z "${ARM_CLIENT_ID:-}" ]]; then
        echo "ARM_CLIENT_ID is missing"
        exit 1
      fi
      echo "ARM variables are populated."
      echo "Tenant: $ARM_TENANT_ID"
      echo "Client: $ARM_CLIENT_ID"

      if [[ -z "${GIT_ACCESS_TOKEN:-}" ]]; then
        echo "GIT_ACCESS_TOKEN is missing"
        exit 1
      fi
      echo "Git Access Token Hash: $(echo -n $GIT_ACCESS_TOKEN | sha256sum | awk '{print $1}')"

    displayName: Validate exported variables
    env:
      ARM_OIDC_TOKEN: $(ARM_OIDC_TOKEN)
      GIT_ACCESS_TOKEN: $(GIT_ACCESS_TOKEN)
